// TEMPORARY DATA

export let role = "admin";

export interface InboxMessage { // Export interface
  id: string;
  sender: {
    avatar: string; // Tetap string untuk URL
    name: string;
  };
  subject: string;
  snippet: string; 
  body: string; 
  timestamp: string;
  isRead: boolean;
  detail?: string; // Opsional jika masih dipakai
}

export const dummyMessages: InboxMessage[] = [ // Export data
  {
    id: "1",
    sender: { name: "Siti Aminah (Wali Kelas)", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3" },
    subject: "Peringatan Absensi",
    snippet: "Selamat pagi, Budi. Saya lihat absensi kamu...",
    body: "Selamat pagi, Budi. \n\nSaya lihat absensi kamu kemarin (Selasa, 21 Okt) Alfa, ada apa ya? Mohon segera konfirmasi ke saya atau bagian tata usaha agar bisa segera ditindaklanjuti.\n\nTerima kasih,\nSiti Aminah, S.Pd.",
    timestamp: "10:30 AM",
    isRead: false,
  },
  {
    id: "2",
    sender: { name: "Admin Sistem", avatar: "/logo.png" },
    subject: "Pembaruan Sistem E-Learning",
    snippet: "Pembaruan sistem akan dilaksanakan pada...",
    body: "Pembaruan sistem akan dilaksanakan pada hari Sabtu pukul 10.00. Sistem mungkin akan nonaktif selama 30 menit. Mohon maaf atas ketidaknyamanannya.",
    timestamp: "Kemarin",
    isRead: true, 
  },
  {
    id: "3",
    sender: { name: "Agus Wijaya (Guru Fisika)", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3" },
    subject: "Tugas Susulan Bab 3",
    snippet: "Bagi yang belum mengumpulkan tugas Bab 3...",
    body: "Bagi yang belum mengumpulkan tugas Bab 3, harap segera dikumpulkan di meja saya paling lambat hari Jumat. Terima kasih.",
    timestamp: "20 Okt 2025",
    isRead: true,
  },
  {
    id: "4",
    sender: { name: "Dewi Lestari (Guru Sejarah)", avatar: "https://images.unsplash.com/photo-1573496359112-58d34C2b3a3b?ixlib=rb-4.0.3" },
    subject: "Pengumuman Kelompok Presentasi",
    snippet: "Berikut adalah pembagian kelompok untuk...",
    body: "Berikut adalah pembagian kelompok untuk presentasi Sejarah minggu depan:\nKelompok 1: Budi, Agus\nKelompok 2: Siti, Dewi\n\nHarap segera diskusikan materinya.",
    timestamp: "19 Okt 2025",
    isRead: false,
  },
  {
    id: "5",
    sender: { name: "Admin Sistem", avatar: "/logo.png" },
    subject: "Perubahan Jadwal Ujian Tengah Semester",
    snippet: "Penting: Ada perubahan jadwal untuk...",
    body: "Penting: Ada perubahan jadwal untuk ujian Matematika dan Fisika. Jadwal terbaru sudah diunggah di halaman 'Event'. Mohon dicek kembali.",
    timestamp: "19 Okt 2025",
    isRead: true,
  },
  {
    id: "6",
    sender: { name: "Tommy Wise (Guru Matematika)", avatar: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-4.0.3" },
    subject: "Nilai Ulangan Harian 2",
    snippet: "Nilai ulangan harian ke-2 sudah bisa...",
    body: "Nilai ulangan harian ke-2 sudah bisa dilihat di menu Nilai. Selamat bagi yang nilainya sudah tuntas!",
    timestamp: "18 Okt 2025",
    isRead: true,
  },
  {
    id: "7",
    sender: { name: "Siti Aminah (Wali Kelas)", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3" },
    subject: "Undangan Rapat Orang Tua Murid",
    snippet: "Yth. Orang Tua/Wali Murid, kami...",
    body: "Yth. Orang Tua/Wali Murid, kami mengundang Bapak/Ibu untuk hadir pada Rapat Pengambilan Rapor Tengah Semester pada hari Sabtu, 25 Oktober 2025.",
    timestamp: "17 Okt 2025",
    isRead: false,
  },
  {
    id: "8",
    sender: { name: "Bruce Rodriguez (Guru IPS)", avatar: "https://images.unsplash.com/photo-1557862921-37829c790f19?ixlib=rb-4.0.3" },
    subject: "Keterlambatan Pengumpulan Tugas Peta",
    snippet: "Budi, tugas peta kamu belum dikumpulkan...",
    body: "Budi, tugas peta kamu belum dikumpulkan. Mohon konfirmasinya segera. Ini adalah peringatan terakhir.",
    timestamp: "17 Okt 2025",
    isRead: true,
  },
  {
    id: "9",
    sender: { name: "Admin Sistem", avatar: "/logo.png" },
    subject: "Kegiatan Class Meeting Pekan Depan",
    snippet: "Dalam rangka mengisi pekan setelah ujian...",
    body: "Dalam rangka mengisi pekan setelah ujian, akan diadakan Class Meeting. Daftar lomba: Futsal, Catur, dan E-Sports. Segera daftarkan kelasmu!",
    timestamp: "16 Okt 2025",
    isRead: true,
  },
  {
    id: "10",
    sender: { name: "Rhoda Frank (Guru B. Inggris)", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib-rb-4.0.3" },
    subject: "Speaking Practice Tambahan",
    snippet: "Bagi yang ingin melatih speaking...",
    body: "Bagi yang ingin melatih speaking, akan ada kelas tambahan online via Zoom pada hari Jumat pukul 14.00. Link akan dibagikan di grup kelas.",
    timestamp: "15 Okt 2025",
    isRead: true,
  },
];

export const teachersData = [
  {
    id: 1,
    teacherId: "198503152010011001",
    name: "Budi Santoso",
    email: "budi.santoso@email.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081234567890",
    subjects: ["Matematika", "Geometri"],
    classes: ["7B", "8A", "9C"],
    address: "Jl. Merdeka No. 10, Jakarta Pusat, DKI Jakarta",
  },
  {
    id: 2,
    teacherId: "198807202012022002",
    name: "Siti Aminah",
    email: "siti.aminah@email.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "087812345678",
    subjects: ["Fisika", "Kimia"],
    classes: ["9A", "8B", "7C"],
    address: "Jl. Pahlawan No. 5, Surabaya, Jawa Timur",
  },
  {
    id: 3,
    teacherId: "198211052008011003",
    name: "Agus Wijaya",
    email: "agus.wijaya@email.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081598765432",
    subjects: ["Biologi"],
    classes: ["9A", "8B", "7C"],
    address: "Jl. Diponegoro No. 22, Bandung, Jawa Barat",
  },
  {
    id: 4,
    teacherId: "199001252015031004",
    name: "Dewi Lestari",
    email: "dewi.lestari@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "085611223344",
    subjects: ["Sejarah"],
    classes: ["9A", "8B", "7C"],
    address: "Jl. Gajah Mada No. 17, Semarang, Jawa Tengah",
  },
  {
    id: 5,
    teacherId: "198609182011012005",
    name: "Rina Hartati",
    email: "rina.hartati@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081355667788",
    subjects: ["Seni Musik", "Sejarah"],
    classes: ["9A", "8B", "7C"],
    address: "Jl. Sudirman No. 3, Medan, Sumatera Utara",
  },
  {
    id: 6,
    teacherId: "199204012018022006",
    name: "Anita Sari",
    email: "anita.sari@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "087799881122",
    subjects: ["Fisika"],
    classes: ["9A", "8B", "7C"],
    address: "Jl. Ahmad Yani No. 88, Makassar, Sulawesi Selatan",
  },
  {
    id: 7,
    teacherId: "198408302009031007",
    name: "Eko Prasetyo",
    email: "eko.prasetyo@email.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081912123434",
    subjects: ["Bahasa Inggris", "Bahasa Spanyol"],
    classes: ["9A", "8B", "7C"],
    address: "Jl. Teuku Umar No. 12, Denpasar, Bali",
  },
  {
    id: 8,
    teacherId: "198905222014022008",
    name: "Putri Anggraini",
    email: "putri.anggraini@email.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "085256567878",
    subjects: ["Matematika", "Geometri"],
    classes: ["9A", "8B", "7C"],
    address: "Jl. Imam Bonjol No. 45, Yogyakarta, DIY",
  },
  {
    id: 9,
    teacherId: "198302112007011009",
    name: "Rahmat Hidayat",
    email: "rahmat.hidayat@email.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081198987676",
    subjects: ["Sastra", "Bahasa Inggris"],
    classes: ["9A", "8B", "7C"],
    address: "Jl. Gatot Subroto No. 60, Palembang, Sumatera Selatan",
  },
  {
    id: 10,
    teacherId: "198712082013031010",
    name: "Joko Susilo",
    email: "joko.susilo@email.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "082145456767",
    subjects: ["Biologi"],
    classes: ["9A", "8B", "7C"],
    address: "Jl. Pattimura No. 9, Pontianak, Kalimantan Barat",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "251001",
    name: "Andi Pratama",
    email: "andi.pratama@emailsekolah.id",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081211112222",
    grade: 7,
    class: "7A",
    address: "Jl. Cendrawasih No. 15, Bogor, Jawa Barat",
  },
  {
    id: 2,
    studentId: "251002",
    name: "Citra Lestari",
    email: "citra.lestari@emailsekolah.id",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "087822223333",
    grade: 8,
    class: "8B",
    address: "Jl. Melati Putih No. 3, Sleman, Yogyakarta",
  },
  {
    id: 3,
    studentId: "251003",
    name: "Fajar Nugroho",
    email: "fajar.nugroho@emailsekolah.id",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "085633334444",
    grade: 9,
    class: "9C",
    address: "Jl. Anggrek No. 8, Tangerang Selatan, Banten",
  },
  {
    id: 4,
    studentId: "251004",
    name: "Bayu Setiawan",
    email: "bayu.setiawan@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081344445555",
    grade: 7,
    class: "7A",
    address: "Jl. Mawar Merah No. 21, Depok, Jawa Barat",
  },
  {
    id: 5,
    studentId: "251005",
    name: "Dian Anggraini",
    email: "dian.anggraini@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "082155556666",
    grade: 8,
    class: "8C",
    address: "Jl. Kenanga Indah No. 11, Bekasi, Jawa Barat",
  },
  {
    id: 6,
    studentId: "251006",
    name: "Nabila Putri",
    email: "nabila.putri@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "087766667777",
    grade: 9,
    class: "9A",
    address: "Jl. Flamboyan No. 7, Jakarta Timur, DKI Jakarta",
  },
  {
    id: 7,
    studentId: "251007",
    name: "Rizky Maulana",
    email: "rizky.maulana@email.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081877778888",
    grade: 7,
    class: "7B",
    address: "Jl. Pahlawan Seribu No. 101, Serpong, Banten",
  },
  {
    id: 8,
    studentId: "251008",
    name: "Fitriani Rahayu",
    email: "fitriani.rahayu@email.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "085388889999",
    grade: 8,
    class: "8A",
    address: "Jl. Kemerdekaan No. 30, Karawang, Jawa Barat",
  },
  {
    id: 9,
    studentId: "251009",
    name: "Aditya Pratama",
    email: "aditya.pratama@email.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081199990000",
    grade: 9,
    class: "9B",
    address: "Jl. Siliwangi No. 55, Cirebon, Jawa Barat",
  },
  {
    id: 10,
    studentId: "251010",
    name: "Gilang Ramadhan",
    email: "gilang.ramadhan@email.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081200001111",
    grade: 7,
    class: "7C",
    address: "Jl. Kartini No. 2, Purwakarta, Jawa Barat",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "John Doe",
    students: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    name: "Jane Doe",
    students: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Matematika",
    teachers: ["Budi Santoso", "Putri Anggraini"],
  },
  {
    id: 2,
    name: "Bahasa Inggris",
    teachers: ["Eko Prasetyo", "Rahmat Hidayat"],
  },
  {
    id: 3,
    name: "Fisika",
    teachers: ["Siti Aminah", "Anita Sari"],
  },
  {
    id: 4,
    name: "Kimia",
    teachers: ["Siti Aminah"],
  },
  {
    id: 5,
    name: "Biologi",
    teachers: ["Agus Wijaya", "Joko Susilo"],
  },
  {
    id: 6,
    name: "Sejarah",
    teachers: ["Dewi Lestari", "Rina Hartati"],
  },
  {
    id: 7,
    name: "Geografi",
    teachers: ["Dewi Lestari", "Eko Prasetyo"],
  },
  {
    id: 8,
    name: "Seni Budaya",
    teachers: ["Rina Hartati"],
  },
  {
    id: 9,
    name: "Pendidikan Jasmani",
    teachers: ["Joko Susilo", "Agus Wijaya"],
  },
  {
    id: 10,
    name: "Sastra Indonesia",
    teachers: ["Rahmat Hidayat"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];
// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDER
// Tanggal telah diubah ke Oktober 2025
export const calendarEvents = [
  // --- Senin, 13 Oktober 2025 ---
  {
    title: "Pendidikan Agama",
    allDay: false,
    start: new Date(2025, 9, 13, 8, 0),
    end: new Date(2025, 9, 13, 8, 45),
  },
  {
    title: "Bahasa Indonesia",
    allDay: false,
    start: new Date(2025, 9, 13, 9, 0),
    end: new Date(2025, 9, 13, 9, 45),
  },
  {
    title: "Matematika",
    allDay: false,
    start: new Date(2025, 9, 13, 10, 0),
    end: new Date(2025, 9, 13, 10, 45),
  },
  {
    title: "IPA (Biologi)",
    allDay: false,
    start: new Date(2025, 9, 13, 11, 0),
    end: new Date(2025, 9, 13, 11, 45),
  },
  {
    title: "IPS (Sejarah)",
    allDay: false,
    start: new Date(2025, 9, 13, 13, 0),
    end: new Date(2025, 9, 13, 13, 45),
  },

  // --- Selasa, 14 Oktober 2025 ---
  {
    title: "PKn",
    allDay: false,
    start: new Date(2025, 9, 14, 8, 0),
    end: new Date(2025, 9, 14, 8, 45),
  },
  {
    title: "Matematika",
    allDay: false,
    start: new Date(2025, 9, 14, 9, 0),
    end: new Date(2025, 9, 14, 9, 45),
  },
  {
    title: "Bahasa Inggris",
    allDay: false,
    start: new Date(2025, 9, 14, 10, 0),
    end: new Date(2025, 9, 14, 10, 45),
  },
  {
    title: "IPA (Fisika)",
    allDay: false,
    start: new Date(2025, 9, 14, 11, 0),
    end: new Date(2025, 9, 14, 11, 45),
  },
  {
    title: "Seni Budaya",
    allDay: false,
    start: new Date(2025, 9, 14, 13, 0),
    end: new Date(2025, 9, 14, 13, 45),
  },
  
  // --- Rabu, 15 Oktober 2025 ---
  {
    title: "Bahasa Indonesia",
    allDay: false,
    start: new Date(2025, 9, 15, 8, 0),
    end: new Date(2025, 9, 15, 8, 45),
  },
  {
    title: "Matematika",
    allDay: false,
    start: new Date(2025, 9, 15, 9, 0),
    end: new Date(2025, 9, 15, 9, 45),
  },
  {
    title: "Bahasa Inggris",
    allDay: false,
    start: new Date(2025, 9, 15, 10, 0),
    end: new Date(2025, 9, 15, 10, 45),
  },
  {
    title: "IPA (Kimia)",
    allDay: false,
    start: new Date(2025, 9, 15, 11, 0),
    end: new Date(2025, 9, 15, 11, 45),
  },
  
  // --- Kamis, 16 Oktober 2025 ---
  {
    title: "Pendidikan Agama",
    allDay: false,
    start: new Date(2025, 9, 16, 8, 0),
    end: new Date(2025, 9, 16, 8, 45),
  },
  {
    title: "TIK",
    allDay: false,
    start: new Date(2025, 9, 16, 9, 0),
    end: new Date(2025, 9, 16, 9, 45),
  },
  {
    title: "IPS (Geografi)",
    allDay: false,
    start: new Date(2025, 9, 16, 10, 0),
    end: new Date(2025, 9, 16, 10, 45),
  },
  {
    title: "Bahasa Indonesia",
    allDay: false,
    start: new Date(2025, 9, 16, 11, 0),
    end: new Date(2025, 9, 16, 11, 45),
  },

  // --- Jumat, 17 Oktober 2025 ---
  {
    title: "Penjas",
    allDay: false,
    start: new Date(2025, 9, 17, 8, 0),
    end: new Date(2025, 9, 17, 8, 45),
  },
  {
    title: "Matematika",
    allDay: false,
    start: new Date(2025, 9, 17, 9, 0),
    end: new Date(2025, 9, 17, 9, 45),
  },
  {
    title: "Bahasa Inggris",
    allDay: false,
    start: new Date(2025, 9, 17, 10, 0),
    end: new Date(2025, 9, 17, 10, 45),
  },

  // --- [BARU] Sabtu, 18 Oktober 2025 ---
 
  {
    title: "Literasi",
    allDay: false,
    start: new Date(2025, 9, 18, 10, 0),
    end: new Date(2025, 9, 18, 10, 45),
  },
  {
    title: "algoritma",
    allDay: false,
    start: new Date(2025, 9, 18, 13, 30),
    end: new Date(2025, 9, 18, 14, 45),
  },
];